#### Tasca M3 T02

Exercicis amb Dataframes.



- Exercici 1
Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un Pandas Dataframe. Explora les dades que conté, explica breument quines variables hi ha i queda’t únicament amb les columnes que consideris rellevants. Justifica la teva elecció.

->Airlines Delay: Airline on-time statistics and delay causes

 Important

Redueix la dimensió del dataset de manera aleatòria per tal d'obtenir un dataset de només 200.000 registres. Tots els exercicis s'han de fer amb aquest dataset reduït.

In [14]:
import pandas as pd

nomfitxer='D:/Users/X/Downloads/DelayedFlights.csv/DelayedFlights.csv'
#llegim el fitxer
fitxer=pd.read_csv(nomfitxer,sep=',')
fitxer[:3]

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [15]:
#definim la primera columna com index i li camviem el nom (l'anomenaré 'Index')
fitxer.rename(columns={'Unnamed: 0':'Index','DayofMonth':'DayOfMonth'},inplace=True)
fitxer.set_index('Index',inplace=True)
fitxer[:3]

,Year,Month,DayOfMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Index,,,,,,,,,,,,,,,,,,,,,
0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,620,804.0,750,WN,448,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [16]:
#volum de dades contingudes
fitxer.shape

(1936758, 29)

In [17]:
#seleccionem una mostra aleatòria de 200k registres
fitxer_reduit=fitxer.sample(n=200000)
fitxer_reduit[:3]
#guardem el fitxer amb 200.000 registres per treballar sempre amb aquest fitxer
fitxer_reduit.to_csv('D:/Users/X/Downloads/DelayedFlights.csv/DelayedFlights_reduit.csv')

In [4]:
import pandas as pd

nomfitxer='D:/Users/X/Downloads/DelayedFlights.csv/DelayedFlights_reduit.csv'
#llegim el fitxer reduit de 200k registres
fitxer=pd.read_csv(nomfitxer,sep=',',index_col='Index')
fitxer[:3]

,Year,Month,DayOfMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
Index,,,,,,,,,,,,,,,,,,,,,
3102296,2008,6,12,4,1747.0,1715,1926.0,1848,XE,2505,...,18.0,31.0,0,N,0,0.0,0.0,6.0,0.0,32.0
3208869,2008,6,27,5,1100.0,1023,1233.0,1209,OO,5851,...,7.0,8.0,0,N,0,24.0,0.0,0.0,0.0,0.0
6888274,2008,12,23,2,1222.0,1215,1352.0,1348,9E,2641,...,9.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [19]:
# Per veure una mostra de totes les columnes, visualitzem el dataframe transposat
fitxer.T

Index,3102296,3208869,6888274,3027929,5854406,117993,3656140,3158277,1622042,458007,...,1216324,3340219,6535865,1157528,3046894,334386,6598429,6260992,3326797,3442094
Year,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008,...,2008,2008,2008,2008,2008,2008,2008,2008,2008,2008
Month,6,6,12,6,10,1,7,6,3,1,...,3,6,12,2,6,1,12,11,6,6
DayOfMonth,12,27,23,12,9,9,18,19,29,15,...,15,5,25,14,18,25,28,12,24,9
DayOfWeek,4,5,2,4,4,3,5,4,6,2,...,6,4,4,4,3,5,7,3,2,1
DepTime,1747.0,1100.0,1222.0,2059.0,1053.0,1008.0,1229.0,1850.0,931.0,1924.0,...,1827.0,1110.0,1956.0,1912.0,2118.0,1927.0,1747.0,2206.0,800.0,1606.0
CRSDepTime,1715,1023,1215,1950,1030,1000,1220,1710,918,805,...,1715,1100,1950,1835,2105,1730,1437,2200,715,1532
ArrTime,1926.0,1233.0,1352.0,2342.0,1232.0,1109.0,1405.0,2150.0,1248.0,2055.0,...,1927.0,1230.0,2223.0,2020.0,2229.0,2226.0,1920.0,2311.0,1032.0,1840.0
CRSArrTime,1848,1209,1348,2240,1210,1114,1400,1924,1230,917,...,1820,1222,2235,2019,2225,2050,1542,2313,1001,1731
UniqueCarrier,XE,OO,9E,WN,AA,XE,WN,OH,NW,9E,...,WN,F9,WN,CO,WN,EV,YV,FL,EV,NW
FlightNum,2505,5851,2641,2047,1461,3120,987,5594,946,2943,...,3350,585,871,1001,96,4520,7260,96,4542,1176
TailNum,N13132,N929SW,86119E,N610WN,N5BUAA,N13566,N624SW,N920CA,N360NB,88839E,...,N248WN,N936FR,N460WN,N76354,N917WN,N827AS,N17156,N949AT,N922EV,N916RW
ActualElapsedTime,99.0,93.0,150.0,103.0,219.0,61.0,156.0,180.0,137.0,91.0,...,60.0,80.0,87.0,128.0,71.0,119.0,93.0,65.0,92.0,154.0
CRSElapsedTime,93.0,106.0,153.0,110.0,220.0,74.0,160.0,134.0,132.0,72.0,...,65.0,82.0,105.0,164.0,80.0,140.0,65.0,73.0,106.0,119.0
AirTime,50.0,78.0,133.0,86.0,200.0,46.0,131.0,83.0,110.0,35.0,...,51.0,62.0,75.0,114.0,59.0,89.0,35.0,51.0,77.0,117.0
ArrDelay,38.0,24.0,4.0,62.0,22.0,-5.0,5.0,146.0,18.0,698.0,...,67.0,8.0,-12.0,1.0,4.0,96.0,218.0,-2.0,31.0,69.0
DepDelay,32.0,37.0,7.0,69.0,23.0,8.0,9.0,100.0,13.0,679.0,...,72.0,10.0,6.0,37.0,13.0,117.0,190.0,6.0,45.0,34.0
Origin,RIC,XNA,BWI,MDW,DFW,ROC,MCO,LGA,MEM,SBN,...,LAX,DEN,MDW,IND,DAL,DSM,IAD,ATL,SHV,MSP
Dest,EWR,ORD,MEM,BWI,SFO,EWR,AUS,CLT,MIA,DTW,...,SJC,SLC,BWI,IAH,MSY,ATL,PIT,RDU,ATL,BNA
Distance,278,522,787,611,1464,246,993,544,860,157,...,308,391,611,845,437,743,183,356,552,695
TaxiIn,18.0,7.0,9.0,4.0,3.0,5.0,4.0,15.0,7.0,7.0,...,3.0,5.0,6.0,4.0,3.0,11.0,42.0,3.0,7.0,7.0
TaxiOut,31.0,8.0,8.0,13.0,16.0,10.0,21.0,82.0,20.0,49.0,...,6.0,13.0,6.0,10.0,9.0,19.0,16.0,11.0,8.0,30.0
Cancelled,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CancellationCode,N,N,N,N,N,N,N,N,N,N,...,N,N,N,N,N,N,N,N,N,N
Diverted,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CarrierDelay,0.0,24.0,NaN,44.0,22.0,NaN,NaN,0.0,13.0,679.0,...,0.0,NaN,NaN,NaN,NaN,0.0,218.0,NaN,31.0,0.0
WeatherDelay,0.0,0.0,NaN,0.0,0.0,NaN,NaN,100.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0
NASDelay,6.0,0.0,NaN,0.0,0.0,NaN,NaN,46.0,5.0,19.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,69.0
SecurityDelay,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0
LateAircraftDelay,32.0,0.0,NaN,18.0,0.0,NaN,NaN,0.0,0.0,0.0,...,67.0,NaN,NaN,NaN,NaN,96.0,0.0,NaN,0.0,0.0

El fitxer conte dades de vols de 2008 amb els temps planificats i reals, i amb detall dels retards i a qui són atribuibles
Descripció de les columnes  
-Year: Any  
-Month: Mes  
-DayofMonth: Día del mes  
-DayOfWeek: Día de la setmana; 1=dilluns  
-DepTime: Hora local de sortida; format hhmm  
-CRSDepTime: Hora local de sortida programada; format hhmm  
-ArrTime: Hora local d'arribada, format hhmm  
-CRSArrTime: Hora local d'arribada prevista; format hhmm  
-UniqueCarrier: Codi d'operador únic  
-FlightNum: Número de vol  
-TailNum: Número d'avió  
-ActualElapsedTime: Temps real transcorregut (en minuts)  
-CRSElapsedTime: temps estimat transcorregut (en minuts)  
-AirTime: Temps de vol (en minuts)  
-ArrDelay: Diferencia entre hora d'arribada prevista i la real, en minuts  
           Les arribades anticipades tenen valor negatiu, en minuts  
-DepDelay: Diferència en minuts entre l'hora de sortida prevista i la real  
           Les sortides anticipades mostren números negatius, en minuts  
-Origin: Codi IATA de l'aeroport origen  
-Dest: Codi IATA de l'aeroprt destí  
-Distance: Distància en milles entre sortida i arribada  
-TaxiIn: Baixada de rodes i arribada a la porta de l'aeroport destí, en minuts  
-TaxiOut: Temps transcorregut entre sortida de l'aeroport origen i aixecament de rodes, en minuts  
-Cancelled: Vol cancel·lat?  
-CancellationCode: Motiu de cancel·lació (A = operador, B = temps, C = sistema nacional d'espai aeri, D = seguretat)  
-Diverted: Avió desviat? 1 = sí, 0 = no  
-CarrierDelay: Temps de retard de l'operador, en minuts  
-WeatherDelay: Temps de retard per causes atmosfèriques  
-NASDelay: Temps de retard per causes del sistema nacional del'espai aeri  
-SecurityDelay: Temps de retard per temes de seguretat, en minuts  
-LateAircraftDelay: Temps de retard per causa atribuible a l'avió

Selecció de columnes  
Per facilitar l'anàlisi estadístic de les dades farem una selecció de les columnes rellevants orientat a l'objectiu d'estudi

In [5]:
import pandas as pd

#creem un nou DataFrame amb les columnes que ens interessen
fitxer_selec=pd.DataFrame(fitxer[['Year','Month','DayOfMonth','DayOfWeek','UniqueCarrier','DepTime','ArrTime','CRSArrTime', \
                                  'ArrDelay','AirTime','Distance','Origin','Dest']])
fitxer_selec

,Year,Month,DayOfMonth,DayOfWeek,UniqueCarrier,DepTime,ArrTime,CRSArrTime,ArrDelay,AirTime,Distance,Origin,Dest
Index,,,,,,,,,,,,,
3102296,2008,6,12,4,XE,1747.0,1926.0,1848,38.0,50.0,278,RIC,EWR
3208869,2008,6,27,5,OO,1100.0,1233.0,1209,24.0,78.0,522,XNA,ORD
6888274,2008,12,23,2,9E,1222.0,1352.0,1348,4.0,133.0,787,BWI,MEM
3027929,2008,6,12,4,WN,2059.0,2342.0,2240,62.0,86.0,611,MDW,BWI
5854406,2008,10,9,4,AA,1053.0,1232.0,1210,22.0,200.0,1464,DFW,SFO
...,...,...,...,...,...,...,...,...,...,...,...,...,...
334386,2008,1,25,5,EV,1927.0,2226.0,2050,96.0,89.0,743,DSM,ATL
6598429,2008,12,28,7,YV,1747.0,1920.0,1542,218.0,35.0,183,IAD,PIT
6260992,2008,11,12,3,FL,2206.0,2311.0,2313,-2.0,51.0,356,ATL,RDU
3326797,2008,6,24,2,EV,800.0,1032.0,1001,31.0,77.0,552,SHV,ATL
3442094,2008,6,9,1,NW,1606.0,1840.0,1731,69.0,117.0,695,MSP,BNA

- Exercici 2
Fes un informe complet del dataset:

Resumeix estadísticament el dataset i les columnes d’interès. Fes una anàlisi estadístic del que consideris rellevant.
Troba quantes dades faltants hi ha per columna.
Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...).
Fes una taula de les aerolínies amb més endarreriments acumulats.
Quins són els vols més llargs? I els més endarrerits? Busca les rutes més llargues i les que acumulen més retards.
Aporta allò que consideris rellevant.

In [107]:
#quines columnes tenen dades amb valor nul
fitxer_selec.isnull().any()

Year             False
Month            False
DayOfMonth       False
DayOfWeek        False
UniqueCarrier    False
DepTime          False
ArrTime           True
CRSArrTime       False
ArrDelay          True
AirTime           True
Distance         False
Origin           False
Dest             False
dtype: bool

In [168]:
#comptem quants valors nuls tenen
fitxer_selec.isnull().sum()

Year                  0
Month                 0
DayOfMonth            0
DayOfWeek             0
UniqueCarrier         0
DepTime               0
ArrTime             740
CRSArrTime            0
ArrDelay            859
AirTime             859
Distance              0
Origin                0
Dest                  0
VelocitatMitjana    859
Tard                  0
dtype: int64

In [169]:
#quines columnes tenen valors no asignats
fitxer_selec.isna().any()

Year                False
Month               False
DayOfMonth          False
DayOfWeek           False
UniqueCarrier       False
DepTime             False
ArrTime              True
CRSArrTime          False
ArrDelay             True
AirTime              True
Distance            False
Origin              False
Dest                False
VelocitatMitjana     True
Tard                False
dtype: bool

In [170]:
#quantes files tenen valors no asignats
fitxer_selec.isna().sum()

Year                  0
Month                 0
DayOfMonth            0
DayOfWeek             0
UniqueCarrier         0
DepTime               0
ArrTime             740
CRSArrTime            0
ArrDelay            859
AirTime             859
Distance              0
Origin                0
Dest                  0
VelocitatMitjana    859
Tard                  0
dtype: int64

In [28]:
#ja que el volum de files amb valors no asignats no es significatiu respecte al volum global, les esborrem
fitxer_selec=fitxer_selec.dropna()
#comptem valors no asignats després d'esborrar
fitxer_selec.isna().sum()
fitxer_selec.shape

(199141, 14)

In [29]:
#Resum estadistic de la mostra

#fitxer_selec.describe()
fitxer_selec[['ArrDelay','AirTime']].describe()

           ArrDelay        AirTime
count  199141.00000  199141.000000
mean       42.26902     108.218177
std        56.96710      68.696437
min       -57.00000       4.000000
25%         9.00000      58.000000
50%        25.00000      90.000000
75%        56.00000     137.000000
max      1344.00000     655.000000

In [30]:
#Nova columna VelocitatMitjana(mph)=distancia/temps de vol en hores
fitxer_selec['VelocitatMitjana']=fitxer_selec['Distance']/(fitxer_selec['AirTime']/60)
fitxer_selec

,Year,Month,DayOfMonth,DayOfWeek,UniqueCarrier,DepTime,ArrTime,CRSArrTime,ArrDelay,AirTime,Distance,Origin,Dest,VelocitatMitjana
Index,,,,,,,,,,,,,,
3102296,2008,6,12,4,XE,1747.0,1926.0,1848,38.0,50.0,278,RIC,EWR,333.600000
3208869,2008,6,27,5,OO,1100.0,1233.0,1209,24.0,78.0,522,XNA,ORD,401.538462
6888274,2008,12,23,2,9E,1222.0,1352.0,1348,4.0,133.0,787,BWI,MEM,355.037594
3027929,2008,6,12,4,WN,2059.0,2342.0,2240,62.0,86.0,611,MDW,BWI,426.279070
5854406,2008,10,9,4,AA,1053.0,1232.0,1210,22.0,200.0,1464,DFW,SFO,439.200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334386,2008,1,25,5,EV,1927.0,2226.0,2050,96.0,89.0,743,DSM,ATL,500.898876
6598429,2008,12,28,7,YV,1747.0,1920.0,1542,218.0,35.0,183,IAD,PIT,313.714286
6260992,2008,11,12,3,FL,2206.0,2311.0,2313,-2.0,51.0,356,ATL,RDU,418.823529
3326797,2008,6,24,2,EV,800.0,1032.0,1001,31.0,77.0,552,SHV,ATL,430.129870
3442094,2008,6,9,1,NW,1606.0,1840.0,1731,69.0,117.0,695,MSP,BNA,356.410256

In [31]:
#Nova columna tard=veritat si 'ArrTime'>'CRSArrTime'
fitxer_selec['Tard']=fitxer_selec['ArrTime']>fitxer_selec['CRSArrTime']
fitxer_selec

,Year,Month,DayOfMonth,DayOfWeek,UniqueCarrier,DepTime,ArrTime,CRSArrTime,ArrDelay,AirTime,Distance,Origin,Dest,VelocitatMitjana,Tard
Index,,,,,,,,,,,,,,,
3102296,2008,6,12,4,XE,1747.0,1926.0,1848,38.0,50.0,278,RIC,EWR,333.600000,True
3208869,2008,6,27,5,OO,1100.0,1233.0,1209,24.0,78.0,522,XNA,ORD,401.538462,True
6888274,2008,12,23,2,9E,1222.0,1352.0,1348,4.0,133.0,787,BWI,MEM,355.037594,True
3027929,2008,6,12,4,WN,2059.0,2342.0,2240,62.0,86.0,611,MDW,BWI,426.279070,True
5854406,2008,10,9,4,AA,1053.0,1232.0,1210,22.0,200.0,1464,DFW,SFO,439.200000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334386,2008,1,25,5,EV,1927.0,2226.0,2050,96.0,89.0,743,DSM,ATL,500.898876,True
6598429,2008,12,28,7,YV,1747.0,1920.0,1542,218.0,35.0,183,IAD,PIT,313.714286,True
6260992,2008,11,12,3,FL,2206.0,2311.0,2313,-2.0,51.0,356,ATL,RDU,418.823529,False
3326797,2008,6,24,2,EV,800.0,1032.0,1001,31.0,77.0,552,SHV,ATL,430.129870,True
3442094,2008,6,9,1,NW,1606.0,1840.0,1731,69.0,117.0,695,MSP,BNA,356.410256,True

In [217]:
fitxer_selec.apply(lambda x: x['Tard'] == True, axis=1).count()

199141

In [32]:
print(fitxer_selec.loc[(fitxer_selec['UniqueCarrier']=='AQ') & (fitxer_selec['Tard']==True)])

         Year  Month  DayOfMonth  DayOfWeek UniqueCarrier  DepTime  ArrTime  \
Index
532950   2008      1          17          4            AQ      5.0    120.0
532594   2008      1           1          2            AQ   1420.0   1455.0
531903   2008      1          19          6            AQ   1911.0   1954.0
532667   2008      1          12          6            AQ   1947.0   2027.0
1104021  2008      2          14          4            AQ   1520.0   1555.0
...       ...    ...         ...        ...           ...      ...      ...
1104903  2008      2           1          5            AQ    703.0    740.0
1104588  2008      2           1          5            AQ   1411.0   1452.0
533199   2008      1           3          4            AQ   1326.0   2110.0
1105510  2008      2          29          5            AQ   1450.0   2155.0
532356   2008      1           7          1            AQ    712.0    743.0

         CRSArrTime  ArrDelay  AirTime  Distance Origin Dest  \
Index
532950           30      50.0     62.0       407    OAK  LAS
532594         1450       5.0     28.0       163    KOA  HNL
531903         1927      27.0     23.0       100    HNL  OGG
532667         1947      40.0     24.0       102    HNL  LIH
1104021        1544      11.0     25.0       100    OGG  HNL
...             ...       ...      ...       ...    ...  ...
1104903         738       2.0     29.0       163    HNL  KOA
1104588        1442      10.0     21.0       100    HNL  OGG
533199         2037      33.0    329.0      2583    HNL  SNA
1105510        2130      25.0    295.0      2349    OGG  OAK
532356          742       1.0     20.0       100    HNL  OGG

         VelocitatMitjana  Tard
Index
532950         393.870968  True
532594         349.285714  True
531903         260.869565  True
532667         255.000000  True
1104021        240.000000  True
...                   ...   ...
1104903        337.241379  True
1104588        285.714286  True
533199         471.063830  True
1105510        477.762712  True
532356         300.000000  True

[82 rows x 15 columns]

In [33]:
#comptem retards per operador
df_retards_per_operador=pd.DataFrame(fitxer_selec.groupby('UniqueCarrier')['Tard'].sum())
df_retards_per_operador
#comptem vols per operador
df_vols_per_operador=pd.DataFrame(fitxer_selec.groupby('UniqueCarrier')['Tard'].count())
df_vols_per_operador
#fem un inner join entre els dos dataframe per disposar del npombre de vols i de retads per operador
#DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=None, indicator=False, validate=None)[source]
df_vols_retards_operador=df_vols_per_operador.merge(df_retards_per_operador,how='inner',on='UniqueCarrier')
#df_vols_retards_operador.info
#type(df_vols_retards_operador)
df_vols_retards_operador.columns=['Vols','Retards']
#calculem el percentatges de retards
df_vols_retards_operador['Tasa']=df_vols_retards_operador['Retards']/df_vols_retards_operador['Vols']*100
df_vols_retards_operador=df_vols_retards_operador.sort_values(by='Tasa',ascending=False)
#Presentem els 10 operados amb tasa mes alta de retards
df_vols_retards_operador.head(10)
#Presentem els 10 operados amb tasa mes baixa de retards
df_vols_retards_operador.tail(10)

                Vols  Retards       Tasa
UniqueCarrier
FL              7316     6343  86.700383
F9              2890     2492  86.228374
AA             19722    16756  84.960957
DL             11668     9869  84.581762
AS              4139     3496  84.464847
WN             38770    32352  83.445963
UA             14793    12269  82.937876
US             10114     8146  80.541823
B6              5609     4421  78.819754
CO             10159     7920  77.960429

In [34]:
#Vols mes llargs
#reset i eliminacio de l'index en un nou dataframe
fitxer_ordenat=fitxer_selec.reset_index(drop=True)
#seleccionem les columnes origem destí i distancia
fitxer_ordenat=pd.DataFrame(fitxer_ordenat[['Origin','Dest','Distance']])
#agrupem els registres per origen, destí i distancia i ens quedem amb un dels registres del grup: el primer
fitxer_ordenat=fitxer_ordenat.groupby(['Origin','Dest','Distance']).first()
#ordenem el fitxer per distancia en ordre decreixent
fitxer_ordenat=fitxer_ordenat.sort_values('Distance', ascending=False)
#mostrem els 10 vols mes llargs
fitxer_ordenat.head(10)

Empty DataFrame
Columns: []
Index: [(EWR, HNL, 4962), (HNL, EWR, 4962), (ATL, HNL, 4502), (HNL, ATL, 4502), (HNL, ORD, 4243), (ORD, HNL, 4243), (KOA, ORD, 4213), (ORD, OGG, 4184), (MSP, HNL, 3972), (HNL, MSP, 3972)]

In [35]:
#Vols mes endarrerits
df_vols_mes_endarrerits=fitxer_selec.sort_values(by='ArrDelay',ascending=False)
df_vols_mes_endarrerits.head(10)

,Year,Month,DayOfMonth,DayOfWeek,UniqueCarrier,DepTime,ArrTime,CRSArrTime,ArrDelay,AirTime,Distance,Origin,Dest,VelocitatMitjana,Tard
Index,,,,,,,,,,,,,,,
3435921,2008,6,16,1,NW,1258.0,1753.0,1929,1344.0,159.0,1300,LAS,MSP,490.566038,False
6939485,2008,12,27,6,AA,1125.0,1434.0,1715,1279.0,98.0,769,HDN,DFW,470.816327,False
2218326,2008,4,5,6,NW,900.0,1404.0,1715,1249.0,165.0,1426,PDX,MSP,518.545455,False
2837951,2008,5,23,5,NW,700.0,823.0,1246,1177.0,56.0,319,BTR,MEM,341.785714,False
747833,2008,2,17,7,NW,903.0,1218.0,1652,1166.0,157.0,1023,GRR,MCO,390.955414,False
2838200,2008,5,21,3,NW,745.0,946.0,1431,1155.0,82.0,488,ALB,DTW,357.073171,False
1674045,2008,3,30,7,AA,640.0,1117.0,1615,1142.0,134.0,1126,PSP,DFW,504.179104,False
2787772,2008,5,16,5,MQ,1101.0,1244.0,1755,1129.0,81.0,500,GPT,DFW,370.370370,False
1625838,2008,3,4,2,NW,922.0,1426.0,2002,1104.0,111.0,622,CLE,MSP,336.216216,False
6850570,2008,12,21,7,MQ,27.0,222.0,759,1103.0,66.0,501,DTW,LGA,455.454545,False

In [36]:
#Rutes que acumulem mes retards
df_rutes_retard=fitxer_selec[['Origin','Dest','ArrDelay']]
df_rutes_retard=df_rutes_retard.reset_index(drop=True)
#fitxer_selec.groupby('UniqueCarrier')['Tard'].sum()
df_rutes_retard
df_rutes_agrupades=pd.DataFrame(df_rutes_retard.groupby(['Origin','Dest'])['ArrDelay'].sum())
df_rutes_agrupades=df_rutes_agrupades.sort_values(by='ArrDelay',ascending=False)
#presentem les 10 rutes amb mes retard acumulat
df_rutes_agrupades.head(10)

             ArrDelay
Origin Dest
LAX    SFO    26353.0
ORD    LGA    25916.0
LGA    ORD    22939.0
ORD    EWR    22222.0
EWR    ORD    18587.0
SFO    LAX    17851.0
DFW    ORD    17345.0
EWR    ATL    17209.0
JFK    BOS    17182.0
ATL    LGA    17035.0

- Exercici 3
Exporta el dataset net i amb les noves columnes a Excel.

In [37]:
import pandas as pd

nomfitxer='D:/Users/X/Downloads/DelayedFlights.csv/MostraVolsRetard.xlsx'
#escrivim el dataframe en el fitxer
fitxer_selec.to_excel(nomfitxer)  
print('Procès finalitzat')

Procès finalitzat